#!name=Apple WLOC 定位修改
#!desc=SourceForge v1.1.0 verified mirror | 设置位置: https://www.icloud.com/shortcuts/a82717d8fdad4e6280866fcf911173f7 | 恢复位置: https://www.icloud.com/shortcuts/f42632d406504f24a2cd163af4fe012f
#!author=Yu9191 Rewrite
#!homepage=https://github.com/atsu6/wloc
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/atsu6/wloc/main/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&randomRadius=0&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/atsu6/wloc/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
